PLAINTEXT_VARIABLES:
  NYPL_API_POST_URL: https://qa-platform.nypl.org/api/v0.1/bibs
  NYPL_API_SCHEMA_URL: https://platform.nypl.org/api/v0.1/current-schemas/BibPostRequest
  NYPL_OAUTH_URL: https://isso.nypl.org/
  NYPL_POST_TYPE: bib
ENCRYPTED_VARIABLES:
  NYPL_OAUTH_KEY: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGswaQYJKoZIhvcNAQcGoFwwWgIBADBVBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDF947sK+52NTSa10VwIBEIAomwBI9nqwJZIg5tU/ntiIE+XZRICMoIWokOvw/mdJwe6Fl8nqw5vliA==
  NYPL_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAycPoBV0IrdXILwm9ECARCAQylQt2/Y0hszSCCv4iDHUwkiSmRPeHHNEvEoXdOJ4Kpyw2RP72354duvdmMlWS/D99fzNr06VwCBnRpMVUNO9wAxXD8=
