PLAINTEXT_VARIABLES:
  NYPL_API_SCHEMA_URL: https://qa-platform.nypl.org/api/v0.1/current-schemas/HoldingPostRequest
  NYPL_POST_TYPE: holding
  NYPL_API_POST_URL: https://qa-platform.nypl.org/api/v0.1/holdings
  NYPL_OAUTH_URL: https://isso.nypl.org/
ENCRYPTED_VARIABLES:
  NYPL_OAUTH_KEY: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGswaQYJKoZIhvcNAQcGoFwwWgIBADBVBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAnpkLoSpXtirNPA9AIBEIAoTSoflouxQdY6hIOAzka6qmFvvJBmfSQYaS7w0sR8y5tK8dXHaZHuOg==
  NYPL_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAy3yeltAOuT3R2LMw0CARCAQ2lbGSgdHq/ID+7hX1a+NRF6/IzoaaY4FewiwH/YPi1pnKFZFeZEPf662HGsxeByYfKObh/WJu3byAzdu548njeIukA=