PLAINTEXT_VARIABLES:
  NYPL_API_POST_URL: https://qa-platform.nypl.org/api/v0.1/items
  NYPL_API_SCHEMA_URL: https://platform.nypl.org/api/v0.1/current-schemas/ItemPostRequest
  NYPL_OAUTH_URL: https://isso.nypl.org/
  NYPL_POST_TYPE: item
ENCRYPTED_VARIABLES:
  NYPL_OAUTH_KEY: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGswaQYJKoZIhvcNAQcGoFwwWgIBADBVBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDPAElO97A3pXOwomTAIBEIAoBzYtd82WMNG6OlsG43TNtEA3va3jTX2H74ARKFVp3c1w08nz5JBRqg==
  NYPL_OAUTH_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwPyYvh3ONbEdCpGAgCARCAQy79ou3upqsOa7/OGH9YieY/DiTG1/Rq8G5i8ZtF6pBI8zGPCH2x28Hbf2Yd7eX229Db2ZB4ojT5fZDjktQtHNqTJV4=
